"use client"

import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Bot,
  BookOpen,
  ExternalLink,
  MessageSquare,
  User,
  FileText,
  Globe,
  GraduationCap,
  ScrollText,
  Layers,
  Lock,
} from "lucide-react"
import type { Course } from "@/lib/types"

type DesignRationaleSection = {
  section: string
  explanation: string
}

type Resource = {
  title: string
  author: string | null
  type: "book" | "paper" | "framework" | "standard" | "online-course" | "documentation" | "website" | "video"
  howItInformedTheCourse: string
  learnerValue: string
  url: string | null
  free: boolean
}

type AiMetadata = {
  model: string
  generatedAt?: string
  designRationale: DesignRationaleSection[]
  resources: Resource[]
  // legacy fields from earlier seeded data — handled gracefully
  considerations?: string[]
  sources?: Array<{ title: string; author: string | null; type: string; relevance: string; url: string | null }>
}

type IntakeAnswer = {
  question: string
  answer: string
}

const RESOURCE_TYPE_ICONS: Record<Resource["type"], React.ReactNode> = {
  book: <BookOpen className="h-3.5 w-3.5" />,
  paper: <FileText className="h-3.5 w-3.5" />,
  framework: <Layers className="h-3.5 w-3.5" />,
  standard: <ScrollText className="h-3.5 w-3.5" />,
  "online-course": <GraduationCap className="h-3.5 w-3.5" />,
  documentation: <FileText className="h-3.5 w-3.5" />,
  website: <Globe className="h-3.5 w-3.5" />,
  video: <Globe className="h-3.5 w-3.5" />,
}

const RESOURCE_TYPE_LABELS: Record<Resource["type"], string> = {
  book: "Book",
  paper: "Paper",
  framework: "Framework",
  standard: "Standard",
  "online-course": "Online course",
  documentation: "Documentation",
  website: "Website",
  video: "Video",
}

export function AboutTab({ course }: { course: Course }) {
  const meta = course.aiMetadata as AiMetadata | null
  const intake = course.intake as IntakeAnswer[] | null

  // Support both new shape (designRationale/resources) and legacy shape (considerations/sources)
  const rationale = meta?.designRationale ?? []
  const resources = meta?.resources ?? []

  // Legacy fallback: if this course was seeded with the old shape, convert considerations → rationale
  const legacySections: DesignRationaleSection[] = (meta?.considerations ?? []).map((text, i) => ({
    section: `Design decision ${i + 1}`,
    explanation: text,
  }))
  const legacyResources: Resource[] = (meta?.sources ?? []).map((s) => ({
    title: s.title,
    author: s.author,
    type: (s.type as Resource["type"]) ?? "website",
    howItInformedTheCourse: s.relevance,
    learnerValue: "Explore this resource to deepen your understanding.",
    url: s.url,
    free: false,
  }))

  const displayRationale = rationale.length > 0 ? rationale : legacySections
  const displayResources = resources.length > 0 ? resources : legacyResources

  const hasContent = displayRationale.length > 0 || displayResources.length > 0 || (intake && intake.length > 0)

  return (
    <div className="mx-auto max-w-3xl space-y-12 py-6">

      {/* Header: model + date */}
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-foreground">About this course</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          This page explains exactly how your course was designed — the sequencing decisions made,
          the frameworks and evidence that informed the content, and the real resources that were used.
          This information is here so you can evaluate the course with full transparency and go deeper
          using the same materials the curriculum was built from.
        </p>
        {meta?.model && (
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 rounded-lg border bg-secondary/40 px-4 py-3 text-sm">
            <Bot className="h-4 w-4 shrink-0 text-muted-foreground" />
            <span className="text-muted-foreground">Generated by</span>
            <span className="font-medium text-foreground">{meta.model}</span>
            {meta.generatedAt && (
              <span className="ml-auto text-muted-foreground">
                {new Date(meta.generatedAt).toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "long",
                  year: "numeric",
                })}
              </span>
            )}
          </div>
        )}
      </section>

      {/* Design Rationale */}
      {displayRationale.length > 0 && (
        <>
          <Separator />
          <section className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-foreground">Why the course was designed this way</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                The AI curriculum designer explains its specific decisions — the topic order, the assumed
                starting point, the pace, the assessment strategy, and any trade-offs made.
              </p>
            </div>
            <div className="space-y-6">
              {displayRationale.map((item, i) => (
                <div key={i} className="flex gap-4">
                  <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                    {i + 1}
                  </div>
                  <div className="space-y-1 pt-0.5">
                    <p className="text-sm font-semibold text-foreground">{item.section}</p>
                    <p className="text-sm leading-relaxed text-muted-foreground">{item.explanation}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </>
      )}

      {/* Resources */}
      {displayResources.length > 0 && (
        <>
          <Separator />
          <section className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-foreground">Resources</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                These are the real materials that informed this course&apos;s content and structure. Each one is
                listed with a specific explanation of how it shaped the curriculum, and what you will gain from
                exploring it yourself. Only resources that genuinely exist are listed here.
              </p>
            </div>
            <div className="space-y-4">
              {displayResources.map((resource, i) => (
                <div
                  key={i}
                  className="rounded-lg border bg-card p-5 space-y-3"
                >
                  {/* Title row */}
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <div className="space-y-0.5 min-w-0">
                      {resource.url ? (
                        <a
                          href={resource.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1.5 font-medium text-foreground hover:text-primary hover:underline"
                        >
                          {resource.title}
                          <ExternalLink className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                        </a>
                      ) : (
                        <p className="font-medium text-foreground">{resource.title}</p>
                      )}
                      {resource.author && (
                        <p className="text-xs text-muted-foreground">{resource.author}</p>
                      )}
                    </div>
                    <div className="flex shrink-0 items-center gap-2">
                      {resource.free ? (
                        <Badge variant="secondary" className="text-xs text-green-700 dark:text-green-400 bg-green-50 dark:bg-green-950/30 border-green-200 dark:border-green-800">
                          Free
                        </Badge>
                      ) : (
                        <Badge variant="secondary" className="text-xs flex items-center gap-1">
                          <Lock className="h-2.5 w-2.5" />
                          Paid
                        </Badge>
                      )}
                      <Badge variant="outline" className="flex items-center gap-1 text-xs">
                        {RESOURCE_TYPE_ICONS[resource.type]}
                        {RESOURCE_TYPE_LABELS[resource.type] ?? resource.type}
                      </Badge>
                    </div>
                  </div>

                  <Separator className="opacity-50" />

                  {/* How it informed the course */}
                  <div className="space-y-1">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">How it shaped this course</p>
                    <p className="text-sm leading-relaxed text-foreground">{resource.howItInformedTheCourse}</p>
                  </div>

                  {/* Learner value */}
                  <div className="space-y-1">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">What you&apos;ll get from it</p>
                    <p className="text-sm leading-relaxed text-muted-foreground">{resource.learnerValue}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </>
      )}

      {/* Personalisation answers */}
      {intake && intake.length > 0 && (
        <>
          <Separator />
          <section className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-foreground">Your personalisation answers</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                The answers you gave when creating this course. These were the brief the AI curriculum
                designer worked from.
              </p>
            </div>
            <div className="space-y-3">
              {intake.map((item, i) => (
                <div key={i} className="rounded-lg border bg-card p-4">
                  <div className="flex gap-3">
                    <User className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
                    <div className="space-y-0.5">
                      <p className="text-sm font-medium text-foreground">{item.question}</p>
                      <p className="text-sm text-muted-foreground">{item.answer}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </>
      )}

      {!hasContent && (
        <div className="rounded-lg border border-dashed p-8 text-center">
          <MessageSquare className="mx-auto mb-3 h-8 w-8 text-muted-foreground/40" />
          <p className="text-sm text-muted-foreground">
            Transparency information is not available for this course.
            Courses created from now on will include full design rationale and resources.
          </p>
        </div>
      )}
    </div>
  )
}
