"use client"

import { Badge } from "@/components/ui/badge"
import { Bot, BookOpen, ExternalLink, Lightbulb, User, MessageSquare } from "lucide-react"
import type { Course } from "@/lib/types"

type AiSource = {
  title: string
  author: string | null
  type: "book" | "paper" | "framework" | "standard" | "course" | "documentation" | "website"
  relevance: string
  url: string | null
}

type AiMetadata = {
  model: string
  generatedAt?: string
  considerations: string[]
  sources: AiSource[]
}

type IntakeAnswer = {
  question: string
  answer: string
}

const SOURCE_TYPE_LABELS: Record<AiSource["type"], string> = {
  book: "Book",
  paper: "Paper",
  framework: "Framework",
  standard: "Standard",
  course: "Course",
  documentation: "Documentation",
  website: "Website",
}

export function AboutTab({ course }: { course: Course }) {
  const meta = course.aiMetadata as AiMetadata | null
  const intake = course.intake as IntakeAnswer[] | null

  return (
    <div className="space-y-10 py-6">
      {/* How this course was built */}
      <section className="space-y-4">
        <div className="flex items-center gap-2">
          <Bot className="h-5 w-5 text-primary" />
          <h2 className="text-lg font-semibold text-foreground">How this course was built</h2>
        </div>
        <p className="text-sm text-muted-foreground">
          This course was generated by an AI curriculum designer using your intake answers as the brief.
          The model, its design decisions, and the sources it drew on are listed below so you can evaluate
          the content with full transparency.
        </p>
        {meta?.model && (
          <div className="flex items-center gap-2 rounded-lg border bg-secondary/40 px-4 py-3 text-sm">
            <Bot className="h-4 w-4 shrink-0 text-muted-foreground" />
            <span className="text-muted-foreground">Generated by</span>
            <span className="font-medium text-foreground">{meta.model}</span>
            {meta.generatedAt && (
              <span className="ml-auto text-muted-foreground">
                {new Date(meta.generatedAt).toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "long",
                  year: "numeric",
                })}
              </span>
            )}
          </div>
        )}
      </section>

      {/* Design considerations */}
      {meta?.considerations && meta.considerations.length > 0 && (
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">Design considerations</h2>
          </div>
          <p className="text-sm text-muted-foreground">
            The key pedagogical decisions the AI made when designing this course.
          </p>
          <ul className="space-y-3">
            {meta.considerations.map((point, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                  {i + 1}
                </span>
                <span className="text-foreground">{point}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Sources */}
      {meta?.sources && meta.sources.length > 0 && (
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <BookOpen className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">Sources &amp; references</h2>
          </div>
          <p className="text-sm text-muted-foreground">
            Authoritative materials that informed this course&apos;s content and structure.
          </p>
          <div className="space-y-3">
            {meta.sources.map((source, i) => (
              <div
                key={i}
                className="flex flex-col gap-2 rounded-lg border bg-card p-4 sm:flex-row sm:items-start sm:gap-4"
              >
                <div className="flex shrink-0 items-center gap-2">
                  <Badge variant="secondary" className="whitespace-nowrap text-xs">
                    {SOURCE_TYPE_LABELS[source.type] ?? source.type}
                  </Badge>
                </div>
                <div className="flex flex-1 flex-col gap-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5">
                    {source.url ? (
                      <a
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 font-medium text-foreground hover:text-primary hover:underline"
                      >
                        {source.title}
                        <ExternalLink className="h-3 w-3 shrink-0" />
                      </a>
                    ) : (
                      <span className="font-medium text-foreground">{source.title}</span>
                    )}
                    {source.author && (
                      <span className="text-sm text-muted-foreground">— {source.author}</span>
                    )}
                  </div>
                  <p className="text-sm text-muted-foreground">{source.relevance}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Your intake answers */}
      {intake && intake.length > 0 && (
        <section className="space-y-4">
          <div className="flex items-center gap-2">
            <MessageSquare className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">Your personalisation answers</h2>
          </div>
          <p className="text-sm text-muted-foreground">
            The answers you gave at course creation. These were used as the brief for the AI
            curriculum designer.
          </p>
          <div className="space-y-3">
            {intake.map((item, i) => (
              <div key={i} className="rounded-lg border bg-card p-4">
                <div className="flex gap-2">
                  <User className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
                  <div className="space-y-1">
                    <p className="text-sm font-medium text-foreground">{item.question}</p>
                    <p className="text-sm text-muted-foreground">{item.answer}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {!meta && !intake && (
        <p className="text-sm text-muted-foreground">
          Transparency information is not available for this course.
        </p>
      )}
    </div>
  )
}
